### ISSUE TITLE
Quantecon and numba error

### ISSUE THREAD

**Issue by shahkirill** [QuantEcon/QuantEcon.py#536]
python 3.7.7 (default, Apr 15 2020, 05:09:04) [MSC v.1916 64 bit (AMD64)]
quantecon-0.4.7
numba-0.49.0

  File "<ipython-input-29-b443e6cedc59>", line 3, in <module>
    import quantecon as qe

  File "C:\Users\ks0063\AppData\Local\Continuum\anaconda3\lib\site-packages\quantecon\__init__.py", line 15, in <module>
    from . import game_theory

  File "C:\Users\ks0063\AppData\Local\Continuum\anaconda3\lib\site-packages\quantecon\game_theory\__init__.py", line 12, in <module>
    from .support_enumeration import support_enumeration, support_enumeration_gen

  File "C:\Users\ks0063\AppData\Local\Continuum\anaconda3\lib\site-packages\quantecon\game_theory\support_enumeration.py", line 14, in <module>
    from ..util.numba import _numba_linalg_solve

  File "C:\Users\ks0063\AppData\Local\Continuum\anaconda3\lib\site-packages\quantecon\util\numba.py", line 15, in <module>
    types.float32: 's',

AttributeError: module 'numba.types' has no attribute 'float32'

**Comment by shahkirill** [comment]
conda update conda
conda update anaconda

**Comment by mmcky** [comment]
Looks like this may have been moved to the top level namespace

```python
from numba import float32
```

**Comment by mmcky** [comment]
thanks for reporting @shahkirill

**Comment by oyamad** [comment]
The `types` submodule is still there at the top level namespace: https://github.com/numba/numba/blob/ff24fb1d32e83602742b548ad1c3aa240f8b34b4/numba/__init__.py#L28

On my environment the following works with `numba=0.49`:

```py
>>> from numba import types
>>> types.float32
float32
```

```py
>>> import numba
>>> numba.__version__
'0.49.0'
```

**Comment by mmcky** [comment]
thanks @oyamad I will have to do some more digging then. You're not getting any deprecation warnings?

**Comment by oyamad** [comment]
No. Are you getting any?

**Comment by mmcky** [comment]
> No. Are you getting any?

reinstalling environments to check.

**Comment by mmcky** [comment]
Thanks @oyamad I am actually getting the same:

```ipython
Python 3.7.7 (default, Mar 26 2020, 10:32:53) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numba                                                                                                                                                                           

In [2]: from numba import types                                                                                                                                                                

In [3]: types.float32                                                                                                                                                                          
Out[3]: float32

In [4]: numba.__version__                                                                                                                                                                      
Out[4]: '0.49.0'
```

All current `nostests` are also passing using the latest `anaconda` and `numba=0.49`

It looks like `types` will be moving in the future so this might still be an issue in `numba>0.49`

@shahkirill can you run the above from `numba`?

**Comment by shahkirill** [comment]
import numba
Traceback (most recent call last):

File "<ipython-input-8-7221fd246eb0>", line 2, in <module>
import numba

File "C:\Users\ks0063\AppData\Local\Continuum\anaconda3\lib\site-packages\numba__init__.py", line 15, in <module>
from numba.core import config

File "C:\Users\ks0063\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\core\config.py", line 16, in <module>
import llvmlite.binding as ll

ModuleNotFoundError: No module named 'llvmlite.binding'

It seems I have issues with numba. Can I use previous versions?

**Comment by oyamad** [comment]
Might be numba/numba#5600.

**Comment by shahkirill** [comment]
Numba has been updated and the issue has disappeared
